branches:
  only:
    - master

version: '{build}'

assembly_info:
  patch: true
  file: '**\SharedAssemblyInfo.*'
  assembly_version: "$(build_version)"
  assembly_file_version: "$(build_version)"
  assembly_informational_version: "$(release_version)"

configuration: Release

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: |
      $buildNumber = [int]$env:APPVEYOR_BUILD_NUMBER
      $regex = [regex]'\[assembly: AssemblyInformationalVersion\(\"(?<version>.*?)\"\)\]'
      $assemblyInfo = Get-Content .\SharedAssemblyInfo.cs
      
      $env:BUILD_VERSION = $regex.Match($assemblyInfo).Groups['version'].Value
      
      "Build version $env:BUILD_VERSION"
      
      $env:RELEASE_VERSION = $env:BUILD_VERSION
      
      if ($env:APPVEYOR_REPO_TAG -ne 'true') {
          $env:RELEASE_VERSION += "-build" + $buildNumber.ToString().PadLeft(5, '0')
          "tag: yes"
      }
      
      "Release version $env:RELEASE_VERSION"

build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true

before_build:
  - ps: nuget restore

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/13degrees/
    api_key:
      secure: 9ztVruXzf0tF7J1efrUsSE2yYqB7uALKcp49ccmLMD4UNqvs3wS99xtrwZEWzwNC
    skip_symbols: true
    on:
      branch: master