branches:
  only:
    - master

version: 0.1.{build}

skip_tags: true

assembly_info:
  patch: true
  file: '**\SharedAssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-beta"

configuration: Release

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

build:
  publish_nuget: true
  publish_nuget_symbols: true

before_build:
  - ps: nuget restore